CREATE SCHEMA db1;
COMMIT;

CREATE TABLE db1.TABMSG
(
    MSG_CODE         INTEGER       NOT NULL,
    MSG_TYPE         DECIMAL(1, 0) NOT NULL CHECK (MSG_TYPE IN (0, 1, 2, 3, 4)),
    MSG_CODE_HOST    CHAR(20)      NOT NULL,
    MSG_TYPE_DE      VARCHAR(254),
    MSG_TYPE_EN      VARCHAR(254),
    PLACEHOLDER_DESC VARCHAR(100),
    PRIMARY KEY (MSG_CODE)
);
COMMIT;

INSERT INTO db1.TABMSG (MSG_CODE, MSG_TYPE, MSG_CODE_HOST, MSG_TYPE_DE, MSG_TYPE_EN, PLACEHOLDER_DESC)
VALUES ('1', 3, '1', 'Ergebnisse', 'results', null);
INSERT INTO db1.TABMSG (MSG_CODE, MSG_TYPE, MSG_CODE_HOST, MSG_TYPE_DE, MSG_TYPE_EN, PLACEHOLDER_DESC)
VALUES ('2', 0, '2', 'Erfolgreich bearbeitet', 'successfully processed', null);
INSERT INTO db1.TABMSG (MSG_CODE, MSG_TYPE, MSG_CODE_HOST, MSG_TYPE_DE, MSG_TYPE_EN, PLACEHOLDER_DESC)
VALUES ('5', 0, '2', 'Erfolgreich aktualisiert', 'successfully updated', null);
COMMIT;

CREATE TABLE db1.TABUSAC
(
    USACCOUNT#KEY   SMALLINT NOT NULL,
    USACCOUNT_DES   CHAR(20) FOR SBCS DATA NOT NULL,
    USACCOUNT_DES_1 CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    USACCOUNT_DES_2 CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    USACCOUNT_DES_3 CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    USACCOUNT_DES_4 CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    CONSTRAINT UNQ_CONS_USACC
        PRIMARY KEY (USACCOUNT#KEY)
);
COMMIT;

CREATE TABLE db1.TAB_LINK_REASON
(
    LINK_REA_ID        INTEGER NOT NULL,
    LINK_REA_WHO_ID    CHAR(1) FOR SBCS DATA NOT NULL,
    LINK_REA_WHOM_ID   CHAR(1) FOR SBCS DATA NOT NULL,
    LINK_REA_SHORT_TXT CHAR(20) FOR SBCS DATA NOT NULL,
    LINK_REA_LONG1_TXT CHAR(50) FOR SBCS DATA NOT NULL,
    LINK_REA_LONG2_TXT CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    LINK_REA_LONG3_TXT CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    LINK_REA_LONG4_TXT CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    LINK_REA_VALID_ID  CHAR(1) FOR SBCS DATA WITH DEFAULT NULL,
    LINK_REA_VAP_ID    CHAR(1) FOR SBCS DATA NOT NULL
        WITH DEFAULT 'J',
    CONSTRAINT UNQ_CONST_LINK_ID
        PRIMARY KEY (LINK_REA_ID)
);
COMMIT;

INSERT INTO db1.TAB_LINK_REASON (LINK_REA_ID, LINK_REA_WHO_ID, LINK_REA_WHOM_ID, LINK_REA_SHORT_TXT, LINK_REA_LONG1_TXT,
                                 LINK_REA_LONG2_TXT, LINK_REA_LONG3_TXT, LINK_REA_LONG4_TXT, LINK_REA_VALID_ID,
                                 LINK_REA_VAP_ID)
VALUES (1, 'A', 'B', 'Linked', 'A and B is linked', '', '', '', '1', 'J');
INSERT INTO db1.TAB_LINK_REASON (LINK_REA_ID, LINK_REA_WHO_ID, LINK_REA_WHOM_ID, LINK_REA_SHORT_TXT, LINK_REA_LONG1_TXT,
                                 LINK_REA_LONG2_TXT, LINK_REA_LONG3_TXT, LINK_REA_LONG4_TXT, LINK_REA_VALID_ID,
                                 LINK_REA_VAP_ID)
VALUES (2, 'A', 'B', 'Linked', 'A and B is linked', '', '', '', '1', 'J');
INSERT INTO db1.TAB_LINK_REASON (LINK_REA_ID, LINK_REA_WHO_ID, LINK_REA_WHOM_ID, LINK_REA_SHORT_TXT, LINK_REA_LONG1_TXT,
                                 LINK_REA_LONG2_TXT, LINK_REA_LONG3_TXT, LINK_REA_LONG4_TXT, LINK_REA_VALID_ID,
                                 LINK_REA_VAP_ID)
VALUES (3, 'A', 'B', 'Linked', 'A and B is linked', '', '', '', '1', 'J');
COMMIT;

CREATE TABLE db1.TAB_CUS_POLICY
(
    CUS_POL_ID         INTEGER      NOT NULL,
    CUS_POL_SHORT_TXT  CHAR(20) FOR SBCS DATA NOT NULL,
    CUS_POL_L1_TXT     CHAR(50) FOR SBCS DATA NOT NULL,
    CUS_POL_L2_TXT     CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    CUS_ACC_PL#KKFOR#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#KKFOR#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#KKFOR#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#KKVER#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#KKVER#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#KKVER#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEFOU#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEFOU#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEFOU#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEFOB#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEFOB#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEFOB#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEVEU#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEVEU#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEVEU#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEVEB#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEVEB#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEVEB#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZEU#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZEU#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZEU#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZEB#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZEB#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZEB#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZAU#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZAU#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZAU#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZAB#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZAB#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZAB#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZE4#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZE4#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZE4#3 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZA4#1 INTEGER      NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZA4#2 SMALLINT     NOT NULL WITH DEFAULT,
    CUS_ACC_PL#TEZA4#3 INTEGER      NOT NULL WITH DEFAULT,
    UPDATE_TS          TIMESTAMP(6) NOT NULL
        WITH DEFAULT,
    CUS_TYPE           CHAR(1) FOR SBCS DATA WITH DEFAULT NULL,
    CUS_SHARE_TYPE     CHAR(1) FOR SBCS DATA WITH DEFAULT NULL,
    PRIMARY KEY (CUS_POL_ID),
    CONSTRAINT CUS_SHARE_TYPE
        CHECK (CUS_SHARE_TYPE IN ('J', 'N') ),
    CONSTRAINT CUS_TYPE
        CHECK (CUS_TYPE IN ('J', 'N') )
);

COMMIT;

CREATE TABLE db1.TAB_USR_INFO
(
    TSUSER            CHAR(8) FOR SBCS DATA NOT NULL,
    TSTIME            TIMESTAMP(6) NOT NULL,
    TSFKT             CHAR(1) FOR SBCS DATA NOT NULL,
    TS_UNTIL          TIMESTAMP(6) NOT NULL,
    SELBSTAUSK_ID     SMALLINT     NOT NULL,
    SELBSTAUSK_DES    CHAR(20) FOR SBCS DATA NOT NULL,
    SELBSTAUSK_L1_DES CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    SELBSTAUSK_L2_DES CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    SELBSTAUSK_L3_DES CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    SELBSTAUSK_L4_DES CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    TS_UPDATE         TIMESTAMP(6) NOT NULL,
    RECHTFRM_ID       SMALLINT     NOT NULL,
    RECHTFRM_DES      CHAR(50) FOR SBCS DATA NOT NULL,
    RECHTFRM_L1_TXT   CHAR(50) FOR SBCS DATA NOT NULL
        WITH DEFAULT,
    RECHTFRM_L2_TXT   CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    RECHTFRM_L3_TXT   CHAR(50) FOR SBCS DATA WITH DEFAULT NULL,
    RECHTFRM_L4_TXT   CHAR(50) FOR SBCS DATA WITH DEFAULT NULL
);
COMMIT;